# -*- coding: utf-8 -*-
"""Hackaton 2 - ML (Logistic Regression).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16gOQo86NinPuY-pcdVSh9eQmK47oHpAK

# Hackaton Clasification
 ----
  
  University : UTEC \\
  Course       : Machine Learning \\
  Professor    : Cristian López Del Alamo \\
  Topic        : Clasification \\
  Deadline      :
   

 ----

Write the names and surnames of the members and the percentage of participation of each one in the development of the practice:
 - Integrante 1: Ian Kevin Condori Flores (100%)
 - Integrante 2: Jean Piero Huaylla Huillca (100%)
 - Integrante 3: Diego Mauricio Marcos Chavez - 202110599 (100%)
 - Integrante 4: Dicson Marcelo Azalde Lazo - 202210034 (100%)

 ----

# <font color='red!3'>Game rules: Read carefully</font>

```
1.  Decídase por un modelo, el que mejor le funcione. Si usa los 3 (SVM, RL o DT), indíquelo en su  ficha de google drive.
2.  Coloque el máximo accuracy alcanzado por su modelo o por sus modelos.
3.  Importante: Use una semilla para replicar su código.
4.  Sólo aquellos códigos en colab que generen exactamente el mismo resultado que los reportados en esta ficha serán tomados en cuenta.




```
Buena Suerte a todos.
"""

#!pip install PyWavelets
import numpy as np
import math
import pandas as pd
import random
import matplotlib.pyplot as plt
import cvxopt
import seaborn as sns
import itertools
#import pywt
import os
from sklearn.metrics import confusion_matrix

"""# Mel-frequency cepstral coefficient
For obtaining the feature vector from the audio file, we will use the mel-frequency cepstral coefficients [(MFCC).](https://speechprocessingbook.aalto.fi/Representations/Melcepstrum.html), and for  obtain this  mel-frequency from an audio, we will use the librosa [library](https://librosa.org/doc/latest/index.html).

----

The following code shows how to load an audio file with librosa and how to play it.
"""

import librosa
import matplotlib.pylab as plt

from IPython.display import Audio
y, sr = librosa.load(librosa.ex('trumpet'))

librosa.display.waveshow(y, sr=sr)
Audio(data=y, rate=sr)

"""# Feacture Vector

To obtain the feature vector, we divide the signal into windows. We will have a total of 20 windows, and from each window, we will extract 230 mel coefficients. We then calculate the average of the coefficients from each window, resulting in a 20-dimensional vector for each audio signal. This vector is the characteristic vector that represents an audio signal.

You and your team can vary the way in which the feature vector is obtained. For example, instead of just taking the average of each window, we could take statistical measures such as the mean, maximum value, minimum value, and standard deviation for each window. These values from all the windows could then be combined into a larger characteristic vecto.

----

The following code shows how to obtein the characteristics vector of an audio using mel coefficients.

"""

y, sr = librosa.load(librosa.ex('trumpet'))
mfccs = librosa.feature.mfcc(y=y, sr=sr)
print("Each windows is represented by a 230-dimensional vector, and the audio has been divided into 20 windows" ,  mfccs.shape)
print("If  we calculate the mean of the coefficients from each of the 20 windows, we will obtain a single 20-dimensional vector. This is the characteristic vector of the audio signal ")
feacture_vector = mfccs.mean(axis = 1)
print(feacture_vector)
print("Vector dimension: " , feacture_vector.shape)

Audio(data=y, rate=sr)

#from google.colab import drive
#drive.mount('/content/drive')

"""# DataSet

Download the dataset from [here](https://drive.google.com/drive/folders/1VfthX0TIhDMsc7rp3ES6ApVwdBLSK4_e?usp=sharing) or simply create a shortcut in your Google Drive.

----

- The following code demonstrates how to load your Google Drive.
- Rewrite the path in case your dataset is located in a different directory on your google drive.
"""

#from google.colab import drive
#drive.mount('/content/drive/')
# "Rewrite the path in case your dataset is located in a different directory on your drive.
path = 'E:\06. Sexto Ciclo\01. Machine Learning\07. Workspace\00.00. Hackathones\06C_Machine_Hackathon\DataSet_Cat_Dog'

"""**"If your directory is correct, you should be able to listen to the following audio**"""

y, sr = librosa.load(path + "/test/dog/dog_barking_15.wav" )
mfccs = librosa.feature.mfcc(y=y, sr=sr)
feacture_vector = np.array(mfccs.mean(axis = 1))
print("Feacture Vector of the dog sound :" , feacture_vector)
Audio(data=y, rate=sr)


# Uncomment to listen to an example of the sound of a cat
# y, sr = librosa.load(path + "/test/cat/cat_88.wav" )
# Audio(data=y, rate=sr)

"""The code provided below accepts the path to your database directory and the type of dataset you wish to load as input. The default dataset is 'train', but you can also opt for 'test'. It returns the feature vectors for all the audio files, along with their labels (1, 0, -1) if you're employing SVM. Should you prefer, the labels can be adjusted to 1 or 0 for use with logistic regression."""

import numpy as np
import os

def extraer_caracteristicas(y, sr):
    """Extrae características avanzadas del audio"""
    mfccs = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=20)

    # Características estadísticas de MFCC
    mfcc_mean = np.mean(mfccs, axis=1)
    mfcc_std = np.std(mfccs, axis=1)
    mfcc_max = np.max(mfccs, axis=1)
    mfcc_min = np.min(mfccs, axis=1)

    zcr = librosa.feature.zero_crossing_rate(y)
    zcr_mean = np.mean(zcr)
    zcr_std = np.std(zcr)

    centroid = librosa.feature.spectral_centroid(y=y, sr=sr)
    centroid_mean = np.mean(centroid)
    centroid_std = np.std(centroid)

    rolloff = librosa.feature.spectral_rolloff(y=y, sr=sr)
    rolloff_mean = np.mean(rolloff)
    rolloff_std = np.std(rolloff)

    bandwidth = librosa.feature.spectral_bandwidth(y=y, sr=sr)
    bandwidth_mean = np.mean(bandwidth)
    bandwidth_std = np.std(bandwidth)

    chroma = librosa.feature.chroma_stft(y=y, sr=sr)
    chroma_mean = np.mean(chroma, axis=1)

    features = np.concatenate([
        mfcc_mean, mfcc_std, mfcc_max, mfcc_min,
        [zcr_mean, zcr_std, centroid_mean, centroid_std,
         rolloff_mean, rolloff_std, bandwidth_mean, bandwidth_std],
        chroma_mean
    ])

    return features

def encode(path, data_type = '/train'):
    data1 = []
    directory_1 = os.listdir(path + data_type + "/cat")
    print(f"Cargando {len(directory_1)} archivos de gatos...")
    for f in directory_1:
        y, sr = librosa.load(path + data_type + "/cat/" + f)
        features = extraer_caracteristicas(y, sr)
        data1.append(features)
    data = np.array(data1)
    # Etiqueta para gatos: 1
    data = np.insert(data, 0, 1, axis=1)

    data2 = []
    directory_2 = os.listdir(path + data_type + "/dog")
    print(f"Cargando {len(directory_2)} archivos de perros...")
    for f in directory_2:
        y, sr = librosa.load(path + data_type + "/dog/" + f)
        features = extraer_caracteristicas(y, sr)
        data2.append(features)
    temp = np.array(data2)
    # Etiqueta para perros: 0
    temp = np.insert(temp, 0, 0, axis=1)

    data = np.concatenate((data, temp), axis=0)
    np.random.shuffle(data)
    y = data[:,0]
    x = data[:, 1:]
    print(f"Vector de características resultante: {x.shape}")
    return x, y

"""# Data Train and Data Test

By this point, your team should already have the training and testing data fully prepared for use in your model. Therefore, your team should focus solely on running your models and achieving good results.
"""

x_train,y_train = encode(path)
x_test, y_test = encode(path, '/test')

import pandas as pd
from sklearn.metrics import confusion_matrix

def matriz_confusion(y_pred,Tipo):
 matrix = confusion_matrix(y_test, y_pred)
 f2 = pd.DataFrame(matrix.astype('float') / matrix.sum(axis=1)[:, np.newaxis], index=["Dog", 'Cat'], columns=["Dog", 'Cat'])
 sns.heatmap(f2, annot=True, cbar=None, cmap="Greens")
 plt.title("Confusion Matrix"  + Tipo ), plt.tight_layout()
 plt.xlabel("Predicted")
 plt.ylabel("Real")
 plt.show()

"""# Model

# Normalizar datos
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

# Normalización de características
def normalizar_datos(x_train, x_test):
    scaler = StandardScaler()
    x_train_norm = scaler.fit_transform(x_train)
    x_test_norm = scaler.transform(x_test)
    return x_train_norm, x_test_norm, scaler

# Verificamos las etiquetas
print(f"Valores únicos en y_train: {np.unique(y_train)}")
print(f"Valores únicos en y_test: {np.unique(y_test)}")

# Dividimos los datos de entrenamiento para tener un conjunto de validación
np.random.seed(42)
indices = np.random.permutation(len(x_train))
val_size = int(0.2 * len(x_train))
val_idx, train_idx = indices[:val_size], indices[val_size:]

x_val, y_val = x_train[val_idx], y_train[val_idx]
x_train_split, y_train_split = x_train[train_idx], y_train[train_idx]

# Normalizamos los datos
x_train_norm, x_val_norm, scaler = normalizar_datos(x_train_split, x_val)
_, x_test_norm, _ = normalizar_datos(x_train_split, x_test)

"""# Definicion de funciones de regresion logistica


El código implementa una regresión logística desde cero. Usa la función sigmoide para obtener probabilidades, calcula el costo con entropía cruzada y un término de regularización, y ajusta los pesos mediante gradiente descendente. Durante el entrenamiento guarda la evolución del costo en entrenamiento y validación. Con los pesos finales puede predecir clases y evaluar la exactitud del modelo.
"""

def sigmoid(z):
    return 1 / (1 + np.exp(-np.clip(z, -500, 500)))

def calcular_costo(X, y, w, lambda_reg=0):
    m = len(y)
    h = sigmoid(np.dot(X, w))
    regularization = (lambda_reg / (2 * m)) * np.sum(w[1:]**2)  # No regularizamos el sesgo (w[0])
    cost = -np.mean(y * np.log(h + 1e-10) + (1 - y) * np.log(1 - h + 1e-10)) + regularization
    return cost

def calcular_gradientes(X, y, w, lambda_reg=0):
    m = len(y)
    h = sigmoid(np.dot(X, w))
    gradients = np.dot(X.T, (h - y)) / m

    if lambda_reg > 0:
        gradients[1:] = gradients[1:] + (lambda_reg / m) * w[1:]

    return gradients

def entrenar_regresion_logistica(X, y, X_val=None, y_val=None, alpha=0.01, num_iteraciones=1000, lambda_reg=0):
    X = np.column_stack((np.ones(X.shape[0]), X))

    if X_val is not None:
        X_val = np.column_stack((np.ones(X_val.shape[0]), X_val))

    m, n = X.shape
    w = np.zeros(n)
    historial_costo = []
    historial_val = []

    for i in range(num_iteraciones):
        costo = calcular_costo(X, y, w, lambda_reg)
        gradientes = calcular_gradientes(X, y, w, lambda_reg)
        w = w - alpha * gradientes

        # Guardar costo cada 50 iteraciones para visualización
        if i % 50 == 0:
            historial_costo.append(costo)

            if X_val is not None and y_val is not None:
                costo_val = calcular_costo(X_val, y_val, w, lambda_reg)
                historial_val.append(costo_val)

    return w, historial_costo, historial_val

def predecir(X, w):
    """Predice la clase usando los pesos entrenados"""
    if X.shape[1] != len(w):
        X = np.column_stack((np.ones(X.shape[0]), X))

    # Aplicar sigmoid y clasificar
    probabilidades = sigmoid(np.dot(X, w))
    predicciones = (probabilidades >= 0.5).astype(int)

    return predicciones, probabilidades

def evaluar_modelo(y_true, y_pred):
    accuracy = accuracy_score(y_true, y_pred)
    return accuracy

def visualizar_entrenamiento(historial_costo, historial_val=None):
    plt.figure(figsize=(10, 6))
    plt.plot(historial_costo, label='Costo de Entrenamiento')

    if historial_val:
        plt.plot(historial_val, label='Costo de Validación')

    plt.title('Evolución de la Función de Costo')
    plt.xlabel('Iteraciones (x50)')
    plt.ylabel('Costo')
    plt.legend()
    plt.grid(True)
    plt.show()

"""# Busqueda de mejores hiperparametros"""

def buscar_mejores_hiperparametros(x_train_norm, y_train_split, x_val_norm, y_val):
    print("Iniciando búsqueda de hiperparámetros...")
    alphas = [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1]
    lambdas = [0, 0.001, 0.01, 0.05, 0.1, 0.5, 1.0]
    max_iteraciones = [1000, 2000, 3000, 5000]

    mejor_acc = 0
    mejores_params = {}

    # Usar una matriz para visualizar resultados
    resultados = np.zeros((len(alphas), len(lambdas)))

    for i, alpha in enumerate(alphas):
        for j, lambda_reg in enumerate(lambdas):
            # Entrenamos el modelo con estos hiperparámetros
            for iter_num in max_iteraciones:
                w, _, _ = entrenar_regresion_logistica(
                    x_train_norm, y_train_split,
                    x_val_norm, y_val,
                    alpha=alpha,
                    num_iteraciones=iter_num,
                    lambda_reg=lambda_reg
                )

                y_val_pred, _ = predecir(x_val_norm, w)
                val_acc = evaluar_modelo(y_val, y_val_pred)

                print(f"Alpha: {alpha}, Lambda: {lambda_reg}, Iteraciones: {iter_num}, Precisión: {val_acc:.4f}")
                resultados[i, j] = val_acc  # Guardamos para visualización

                if val_acc > mejor_acc:
                    mejor_acc = val_acc
                    mejores_params = {
                        'alpha': alpha,
                        'lambda_reg': lambda_reg,
                        'num_iteraciones': iter_num
                    }

    # Visualizamos los resultados en un heatmap
    plt.figure(figsize=(12, 8))
    sns.heatmap(resultados, annot=True, cmap='viridis',
                xticklabels=lambdas, yticklabels=alphas)
    plt.xlabel('Lambda (Regularización)')
    plt.ylabel('Alpha (Tasa de aprendizaje)')
    plt.title('Precisión de validación para diferentes hiperparámetros')
    plt.show()

    print("\nMejores hiperparámetros encontrados:")
    print(f"Alpha: {mejores_params['alpha']}")
    print(f"Lambda: {mejores_params['lambda_reg']}")
    print(f"Iteraciones: {mejores_params['num_iteraciones']}")
    print(f"Mejor precisión en validación: {mejor_acc:.4f}")

    return mejores_params

"""# Visualizacion de resultados y ejecucon de codigo

Primero, verifica que las etiquetas de entrenamiento y prueba estén correctas. Luego, divide los datos de entrenamiento en un subconjunto de entrenamiento y otro de validación, asegurando reproducibilidad con una semilla aleatoria. Después, normaliza los datos y realiza una búsqueda de hiperparámetros (tasa de aprendizaje, número de iteraciones y regularización) para encontrar la mejor configuración del modelo.

Con esos hiperparámetros, entrena el modelo de regresión logística manual, guarda la evolución de la función de costo y evalúa la precisión tanto en validación como en prueba. También muestra la matriz de confusión y un reporte con métricas de clasificación (precisión, recall y F1).

Finalmente, entrena un modelo equivalente con Scikit-learn usando los mismos hiperparámetros, predice sobre los datos de prueba y compara su desempeño con el modelo implementado manualmente, mostrando igualmente matriz de confusión y métricas.
"""

# Verificamos las etiquetas
print(f"Valores únicos en y_train: {np.unique(y_train)}")
print(f"Valores únicos en y_test: {np.unique(y_test)}")

# Dividimos los datos de entrenamiento para tener un conjunto de validación
np.random.seed(42)  # Semilla para reproducibilidad
indices = np.random.permutation(len(x_train))
val_size = int(0.2 * len(x_train))
val_idx, train_idx = indices[:val_size], indices[val_size:]

x_val, y_val = x_train[val_idx], y_train[val_idx]
x_train_split, y_train_split = x_train[train_idx], y_train[train_idx]

# Normalizamos los datos
x_train_norm, x_val_norm, scaler = normalizar_datos(x_train_split, x_val)
_, x_test_norm, _ = normalizar_datos(x_train_split, x_test)

# Búsqueda de hiperparámetros óptimos
mejores_params = buscar_mejores_hiperparametros(x_train_norm, y_train_split, x_val_norm, y_val)

# Hiperparámetros óptimos
alpha = mejores_params['alpha']
num_iteraciones = mejores_params['num_iteraciones']
lambda_reg = mejores_params['lambda_reg']

print(f"\nEntrenando modelo final con alpha={alpha}, lambda={lambda_reg}, iteraciones={num_iteraciones}")

# Entrenamos el modelo con los mejores hiperparámetros
w, historial_costo, historial_val = entrenar_regresion_logistica(
    x_train_norm, y_train_split,
    x_val_norm, y_val,
    alpha=alpha,
    num_iteraciones=num_iteraciones,
    lambda_reg=lambda_reg
)

# Visualizamos la función de costo
visualizar_entrenamiento(historial_costo, historial_val)

# Evaluamos en el conjunto de validación
y_val_pred, _ = predecir(x_val_norm, w)
val_accuracy = evaluar_modelo(y_val, y_val_pred)
print(f"Precisión en el conjunto de validación: {val_accuracy:.4f}")

# Evaluamos en el conjunto de prueba
y_pred, _ = predecir(x_test_norm, w)
test_accuracy = evaluar_modelo(y_test, y_pred)
print(f"Precisión en el conjunto de prueba: {test_accuracy:.4f}")

# Mostramos la matriz de confusión
matriz_confusion(y_pred, " Regresión Logística Manual Mejorado ")

# Mostramos el reporte de clasificación
report = classification_report(y_test, y_pred, target_names=["Dogs", "Cats"])
print("Métricas del Modelo de Regresión Logística Manual Mejorado:")
print(report)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Creamos y entrenamos el modelo de scikit-learn con los mejores hiperparámetros
# Manejo del caso cuando lambda_reg es 0
if lambda_reg == 0:
    C = 1000  # Un valor grande para C cuando no hay regularización
else:
    C = 1/lambda_reg

modelo_sklearn = LogisticRegression(random_state=42, C=C, max_iter=num_iteraciones)
modelo_sklearn.fit(x_train_norm, y_train_split)

# Predecimos en el conjunto de prueba
y_pred_sklearn = modelo_sklearn.predict(x_test_norm)

# Evaluamos el modelo
accuracy_sklearn = accuracy_score(y_test, y_pred_sklearn)
print(f"Precisión con scikit-learn: {accuracy_sklearn:.4f}")

# Comparamos con nuestro modelo personalizado
print(f"Precisión con nuestro modelo mejorado: {test_accuracy:.4f}")

# Mostramos la matriz de confusión
matriz_confusion(y_pred_sklearn, " Regresión Logística Sklearn Optimizado ")

# Mostramos el reporte de clasificación
report_sklearn = classification_report(y_test, y_pred_sklearn, target_names=["Dogs", "Cats"])
print("Métricas del Modelo de Regresión Logística de Scikit-learn Optimizado:")
print(report_sklearn)